version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: testing123
      POSTGRES_USER: user@test
      POSTGRES_DB: mydb
    volumes:
      - mydata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
  
  backend:
    image: golang:latest
    ports:
      - 8080:8080
    volumes: 
      - ./:/backend/
    working_dir: /backend/cmd/
    command: ["go", "run", "main.go"]

volumes:
  mydata:
