name: Go

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches: [ master ]

jobs:
  restapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: format
      run: go fmt ./...

    - name: Test
      run: go test -v ./...
      
    - name: done
      run: echo "completed"
